version: '3.8'
services:
  postgres-users:
    image: postgres:15
    container_name: bookstore_postgres_users
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user_svc_user} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-user_svc_password}
      POSTGRES_DB: ${POSTGRES_DB_USERS:-users_db}
    ports:
      - "${POSTGRES_PORT_USERS:-5433}:5432"
    volumes:
      - postgres_users_data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres-books: 
    image: postgres:15
    container_name: bookstore_postgres_books
    environment:
      POSTGRES_USER: ${POSTGRES_USER_BOOKS:-book_svc_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_BOOKS:-book_svc_password}
      POSTGRES_DB: ${POSTGRES_DB_BOOKS:-books_db}
    ports:
      - "${POSTGRES_PORT_BOOKS:-5434}:5432"
    volumes:
      - postgres_books_data:/var/lib/postgresql/data 
    restart: unless-stopped

  postgres-reading-progress: 
    image: postgres:15
    container_name: bookstore_postgres_reading_progress
    environment:
      POSTGRES_USER: ${POSTGRES_USER_READING:-reading_svc_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_READING:-reading_svc_password}
      POSTGRES_DB: ${POSTGRES_DB_READING:-reading_progress_db}
    ports:
      - "${POSTGRES_PORT_READING:-5435}:5432" 
    volumes:
      - postgres_reading_data:/var/lib/postgresql/data 
    restart: unless-stopped

volumes:
  postgres_users_data:
  postgres_books_data:
  postgres_reading_data: