services:
  postgres_users:
    image: postgres:15
    container_name: bookstore_postgres_users
    environment:
      POSTGRES_USER: users_user 
      POSTGRES_PASSWORD: users_pass 
      POSTGRES_DB: users_db 
    ports:
      - "5433:5432"
    volumes:
      - bookstore_postgres_users_data:/var/lib/postgresql/data
    networks:
      - bookstore_network

  postgres_books:
    image: postgres:15
    container_name: bookstore_postgres_books
    environment:
      POSTGRES_USER: books_user
      POSTGRES_PASSWORD: books_pass 
      POSTGRES_DB: books_db 
    ports:
      - "5434:5432"
    volumes:
      - bookstore_postgres_books_data:/var/lib/postgresql/data
    networks:
      - bookstore_network

  postgres_reading_progress:
    image: postgres:15
    container_name: bookstore_postgres_reading_progress
    environment:
      POSTGRES_USER: reading_user 
      POSTGRES_PASSWORD: reading_pass
      POSTGRES_DB: reading_db 
    ports:
      - "5435:5432"
    volumes:
      - bookstore_postgres_reading_data:/var/lib/postgresql/data
    networks:
      - bookstore_network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_bookstore
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com" 
      PGADMIN_DEFAULT_PASSWORD: "admin" 
    ports:
      - "5050:80" # http://localhost:5050
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - bookstore_network 
    depends_on:
      - postgres_users
      - postgres_books
      - postgres_reading_progress
  # ------------------------


volumes:
  bookstore_postgres_users_data:
  bookstore_postgres_books_data:
  bookstore_postgres_reading_data:
  pgadmin_data: 

networks:
  bookstore_network: 
    driver: bridge
