
services:
  postgres-users: # Service name for the users database
    image: postgres:15 # Using a specific version is good practice
    container_name: bookstore_postgres_users
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user} # Use environment variables or defaults
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-users_db}
    ports:
      - "${POSTGRES_PORT:-5433}:5432" # Map a host port (e.g., 5433) to container's 5432
    volumes:
      - postgres_users_data:/var/lib/postgresql/data # Persist data
    restart: unless-stopped

volumes:
  postgres_users_data: # Defines the named volume